### ISSUE TITLE
Problem to search SNPs in primers by sequence

### ISSUE THREAD

**Issue by JiguiS** [Benoitdw/SNPrimer#2]
Alway returns message like: "INFO PositionRange(chr='chr1', start=26774827, end=26774847, strand='+', snp=[]) is not initialised". Could you please let me know what I'm missing? 
Thank you!
Jonathan

**Comment by JiguiS** [comment]
Never mind. I've resolved the issue by making a modification in primer.py. I changed the init_snp parameter to True instead of False when calling PositionRange(), and now everything is working perfectly. Thank you!

**Comment by Benoitdw** [comment]
Hello ! 
Thank you for using this library.
You also can loop on the `hybridization_place` attribute of your primer and call `search_snp()` for each of them.

```python
for place in primer.hybridization_place:
    place.search_snp()
```

Hope it will help ! :)

**Comment by JiguiS** [comment]
Hello!

Thank you for the information! Your work is greatly appreciated, and your libraries are invaluable resources for developers, including those working on primer design like me. I've integrated it into my project, and it's working smoothly so far. Have a wonderful day! Thank you again for your kind help!
________________________________
